version: '3'
services:
  demoapp:
    build: .
    ports:
      - "8080:8080"

  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes:
    - "./grafana:/var/lib/grafana"
    user: "${UID:?\"Please run using 'UID=$(id -u):$(id -g) docker-compose up'\" command}"

  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"